---
title: "Clinical Trials"
subtitle: "A Hands-on Workshop"
author: "Prof. Ashraf Nabhan"
subject: "Research"
title-meta: "Clinical Trials Workshop"
author-meta: "Prof. A. Nabhan"
format: 
  revealjs:
    theme: solarized
    css: styles.css
    toc: true
    toc-title: "Agenda"
    toc-depth: 1
---

# Clinical trial Methods: A Recap

## The essentials

- **Type of trial**: parallel, multi-arm, cross-over

- **Framework**: superiority, non-inferiority

- **Controlled**: no control, placebo, active

- **Phase**: Only for drug trials

## Allocation

- **Allocation**:
  - Non-random
  - Quasi-random
  - Random
- **Unit of allocation**:
  - individual
  - cluster

# Sample size calculation

## What a researcher should do

- Estimate the number of participants needed to achieve study objectives

- Describe how it was determined

- Indicate clinical and statistical assumptions supporting calculations.

## Practical exercise

- Clinical question
  - Among ICU patients with septic shock and AKI without urgent need for dialysis, does an early, compared to delayed, initiation of renal replacement therapy reduce all-cause mortality at 90 days?

## The study hypothesis

- The null and alternative hypotheses are:
  - **H~0~ : P~t~ - P~c~ = 0**​
  - **H~1~ : P~t~ - P~c~ ≠ 0**​

## Arguments

- the expected proportion for the treatment group
- the expected proportion for the control group
- the equivalence limit
- the required study power
- the desired alpha level
- sided.test

## Clinical and statistical assumptions

- treat = .4
- control = .5
- delta = 0
- power = .8
- alpha = .05
- sided.test = 2

## Calculation

- use our online tool <https://ecebm.shinyapps.io/Power>

- use epiR package in R:

  - epi.sssupb(n = NA, treat = .4, control = .5, delta = 0, power = .8, alpha = .05, sided.test = 2)

- The estimated sample size is 770 \[385 participants per arm\]

# Random allocation

## Simple random allocation

- Equal probability

- Unpredictability

- No guarantee of balance

## Random allocation rule

- Forced equal allocation

- Vulnerability to selection bias late in trial

## Block randomization

- Balanced allocation within blocks

- Protection against temporal trends

- Predictability risk with fixed block sizes

## Tools

- use R functions

- use our online tool <https://ecebm.shinyapps.io/randalloc>

# Clinical trial registration

## Open access primary registries

- is Mandatory

- Example

  - PACTR
  - Clinicaltrials.gov

- Use SPIRIT for the protocol

  - Perfectly aligns with trial registries

# Learning from mistakes

## Comments: RCT

1.  Selection bias

2.  Serious contradiction in retinopathy inclusion criterion

3.  Only one HbA1c measurement at the end of follow up

4.  Intervention was not standardized

5.  Composite outcome problem

6.  Follow-up Duration

# Discussion and ideas